FROM python:3.11-slim

# Environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PATH="/root/.cargo/bin:$PATH"

WORKDIR /app

# System dependencies and Rust toolchain
RUN apt-get update && apt-get install -y \
    curl \
    gcc \
    g++ \
    ccache \
    libgl1 \
    libglib2.0-0 \
    ffmpeg \
    git \
    wget \
    pkg-config \
    libssl-dev \
    build-essential \
    libffi-dev \
    python3-dev \
    rustc \
    cargo \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Python dependencies
COPY requirements.txt ./
RUN pip install --upgrade pip
RUN pip install --use-pep517 --no-cache-dir -r requirements.txt

# BLIP (editable install)
RUN pip install -e git+https://github.com/pharmapsychotic/BLIP.git@lib#egg=blip

# Optional: Clone clip-interrogator
RUN git clone -b open-clip https://github.com/pharmapsychotic/clip-interrogator.git

# Optional: Cache files
RUN mkdir -p /app/cache && \
  wget https://huggingface.co/pharma/ci-preprocess/resolve/main/ViT-H-14_laion2b_s32b_b79k_artists.pkl -P /app/cache && \
  wget https://huggingface.co/pharma/ci-preprocess/resolve/main/ViT-H-14_laion2b_s32b_b79k_flavors.pkl -P /app/cache && \
  wget https://huggingface.co/pharma/ci-preprocess/resolve/main/ViT-H-14_laion2b_s32b_b79k_mediums.pkl -P /app/cache && \
  wget https://huggingface.co/pharma/ci-preprocess/resolve/main/ViT-H-14_laion2b_s32b_b79k_movements.pkl -P /app/cache && \
  wget https://huggingface.co/pharma/ci-preprocess/resolve/main/ViT-H-14_laion2b_s32b_b79k_trendings.pkl -P /app/cache

# Copy app code
COPY . .

EXPOSE 8000
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
