name: Deploy to Local

on:
  push:
    branches:
      - main

jobs:
  deploy_to_local:
    runs-on: [dgx-2]

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4

      - name: Build Image
        run: |
          docker build -t imgen:dev .
      
      - name: Remove Existing Docker
        run: |
          docker stop imgen || true
          docker rm imgen || true
    
      - name: Deploy to Docker
        run: |
          docker run -d --gpus all --privileged\
            -e HUGGINGFACE_TOKEN=${{ secrets.HUGGINGFACE_TOKEN }} \
            -p 8016:8000 --name imgen imgen:dev

    environment:
      name: env