name: Deploy to Local

on:
  push:
    branches:
      - main

jobs:
  deploy_to_local:
    runs-on: [dgx-2]

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4

      - name: Stop existing containers
        run: |
          docker stop imgen redis rq_worker || true
          docker rm imgen redis rq_worker || true

      - name: Start Redis
        run: |
          docker run -d --name redis -p 6379:6379 redis:7

      - name: Build FastAPI App Image
        run: |
          docker build -t imgen:dev .

      - name: Run FastAPI App
        run: |
          docker run -d --gpus all --privileged \
            --name imgen \
            -e HUGGINGFACE_TOKEN=${{ secrets.HUGGINGFACE_TOKEN }} \
            --link redis \
            -v /home/prepaire/ttm/output:/app/output \
            -p 8016:8000 \
            imgen:dev

      - name: Run RQ Worker
        run: |
          docker run -d --gpus all --privileged \
            --name rq_worker \
            -e HUGGINGFACE_TOKEN=${{ secrets.HUGGINGFACE_TOKEN }} \
            --link redis \
            -v /home/prepaire/ttm/output:/app/output \
            imgen:dev \
            python worker.py

    environment:
      name: env
